from __future__ import annotations

from enum import StrEnum


class ConfidenceLabel(StrEnum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    VERY_LOW = "VERY_LOW"


class ModelClassification(StrEnum):
    PRIMARY = "PRIMARY"
    SECONDARY = "SECONDARY"
    WATCH = "WATCH"
    NO_BET = "NO_BET"
    NOT_ELIGIBLE = "NOT_ELIGIBLE"


class CombinationFilterStatus(StrEnum):
    QUALIFIED = "QUALIFIED"
    FALLBACK = "FALLBACK"


class UserActionLabel(StrEnum):
    RECOMMENDED = "RECOMENDADO"
    OPTIONAL = "OPCIONAL"
    PASS = "PASAR"


class MarketPriceLabel(StrEnum):
    GOOD_VALUE = "PRECIO BUENO"
    FAIR = "PRECIO JUSTO"
    BAD_PRICE = "MAL PRECIO"
    NO_ODDS = "SIN CUOTA"
    MARKET_PASS = "PASAR PRECIO"


class IntegrityStatus(StrEnum):
    PASS = "PASS"
    FAIL = "FAIL"
    WAITING = "WAITING"


class ModelHealth(StrEnum):
    GREEN = "GREEN"
    YELLOW = "YELLOW"
    RED = "RED"


class SlateQuality(StrEnum):
    GREEN = "GREEN"
    YELLOW = "YELLOW"
    RED = "RED"


class CriticVerdict(StrEnum):
    PASS = "PASS"
    CAUTION = "CAUTION"
    REJECT = "REJECT"


class WarningSeverity(StrEnum):
    MINOR = "MINOR"
    MAJOR = "MAJOR"
    CRITICAL = "CRITICAL"


class RoofStatus(StrEnum):
    OPEN = "OPEN"
    CLOSED = "CLOSED"
    FIXED_DOME = "FIXED_DOME"
    UNKNOWN = "UNKNOWN"


class GameState(StrEnum):
    SCHEDULED = "SCHEDULED"
    PREGAME = "PREGAME"
    LIVE = "LIVE"
    FINAL = "FINAL"
    POSTPONED = "POSTPONED"
    SUSPENDED = "SUSPENDED"
    CANCELLED = "CANCELLED"
    UNKNOWN = "UNKNOWN"


class SettlementStatus(StrEnum):
    PREGAME_LOCKED = "PREGAME_LOCKED"
    WAITING_FOR_GAME = "WAITING_FOR_GAME"
    LIVE = "LIVE"
    FINAL_PENDING_RECONCILIATION = "FINAL_PENDING_RECONCILIATION"
    PROVISIONAL_SETTLEMENT = "PROVISIONAL_SETTLEMENT"
    CONFIRMED_SETTLEMENT = "CONFIRMED_SETTLEMENT"
    SUSPENDED = "SUSPENDED"
    POSTPONED = "POSTPONED"
    CANCELLED = "CANCELLED"
    VOID = "VOID"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"


class PlayerAppearanceStatus(StrEnum):
    STARTED_AND_BATTED = "STARTED_AND_BATTED"
    STARTED_NO_COMPLETED_PA = "STARTED_NO_COMPLETED_PA"
    DID_NOT_APPEAR = "DID_NOT_APPEAR"
    LATE_SCRATCH = "LATE_SCRATCH"
    SUBSTITUTED = "SUBSTITUTED"
    UNKNOWN = "UNKNOWN"


class DataFreshness(StrEnum):
    FRESH = "FRESH"
    WARNING = "WARNING"
    STALE = "STALE"
    UNKNOWN = "UNKNOWN"


class HistoryClass(StrEnum):
    ESTABLISHED_MLB = "ESTABLISHED_MLB"
    LIMITED_MLB = "LIMITED_MLB"
    MLB_PLUS_TRACKED_MINORS = "MLB_PLUS_TRACKED_MINORS"
    TRACKED_MINORS_ONLY = "TRACKED_MINORS_ONLY"
    MINIMAL_HISTORY = "MINIMAL_HISTORY"
    RETURNING_OR_ROLE_CHANGE = "RETURNING_OR_ROLE_CHANGE"


class ProfileChangeStatus(StrEnum):
    NO_CONFIRMED_CHANGE = "NO_CONFIRMED_CHANGE"
    POSSIBLE_CHANGE = "POSSIBLE_CHANGE"
    STRUCTURAL_CHANGE = "STRUCTURAL_CHANGE"
    RECOVERING_PROFILE = "RECOVERING_PROFILE"
    TRANSITION_PROFILE = "TRANSITION_PROFILE"


class StarterRole(StrEnum):
    STANDARD_STARTER = "STANDARD_STARTER"
    LIMITED_STARTER = "LIMITED_STARTER"
    WORKHORSE_STARTER = "WORKHORSE_STARTER"
    OPENER = "OPENER"
    BULK_PITCHER = "BULK_PITCHER"
    SPOT_STARTER = "SPOT_STARTER"
    RETURNING_LIMITED = "RETURNING_LIMITED"
    PITCH_LIMIT_EXPECTED = "PITCH_LIMIT_EXPECTED"
    BULLPEN_GAME = "BULLPEN_GAME"
    UNKNOWN_ROLE = "UNKNOWN_ROLE"


class ReliefRole(StrEnum):
    CLOSER = "CLOSER"
    SETUP = "SETUP"
    MIDDLE_RELIEF = "MIDDLE_RELIEF"
    LONG_RELIEF = "LONG_RELIEF"
    BULK = "BULK"
    MULTI_INNING = "MULTI_INNING"
    LOW_LEVERAGE = "LOW_LEVERAGE"
    UNKNOWN = "UNKNOWN"
